### ISSUE TITLE
Changing Player NBT not saving

### ISSUE THREAD

**Issue by BluXDragon** [FallenMoonNetwork/CanaryLib#105]
Example code is best code.

```
        //Tasty tasty NBT
        CompoundTag nbt = targetPlayer.getNBT();

        nbt.put("RepPoints", 10);
        caller.message("1: "+nbt.getInt("RepPoints")); //returns 10

        nbt.put("RepPoints", 20);
        caller.message("2: "+nbt.getInt("RepPoints")); //returns 20

        //Let's gather the NBT again
        nbt = targetPlayer.getNBT(); 
        caller.message("3: "+nbt.getInt("RepPoints")); //returns 0
```

Additionally I attempted setNBT as a result of the above, with these results;
player.setNBT(nbt); where nbt is player.getNBT(); throws this;

```
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.canarymod.commandsys.CommandManager$1.execute(CommandManager.java:245)
        at net.canarymod.commandsys.CanaryCommand.parseCommand(CanaryCommand.java:63)
        at net.canarymod.commandsys.CommandManager.parseCommand(CommandManager.java:134)
        at net.canarymod.api.entity.living.humanoid.CanaryPlayer.executeCommand(CanaryPlayer.java:296)
        at net.canarymod.api.entity.living.humanoid.CanaryPlayer.chat(CanaryPlayer.java:110)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:611)
        at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:40)
        at net.minecraft.server.TcpConnection.b(TcpConnection.java:284)
        at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:71)
        at net.minecraft.server.NetworkListenThread.b(NetworkListenThread.java:32)
        at net.minecraft.server.DedicatedServerListenThread.b(DedicatedServerListenThread.java:24)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:481)
        at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:206)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:396)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:335)
        at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:13)
Caused by: net.minecraft.server.ReportedException: Loading entity NBT
        at net.minecraft.server.Entity.f(Entity.java:1063)
        at net.canarymod.api.entity.CanaryEntity.setNBT(CanaryEntity.java:306)
        at net.mineworld.mineworld.reputation.ReputationHandler.setReputationPoints(ReputationHandler.java:28)
        at net.mineworld.mineworld.reputation.ReputationCommands.commandReputationSet(ReputationCommands.java:68)
        ... 20 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at net.minecraft.server.NBTTagList.b(NBTTagList.java:68)
        at net.minecraft.server.Entity.f(Entity.java:1021)
        ... 23 more
```

**Comment by darkdiplomat** [comment]
1) NBT is created on the fly and uses the fields already present in the entity, so using the default NBT Tags will result in only the one instance having that data.

2) Someone should have included a meta tag for entities

**Comment by darkdiplomat** [comment]
a87d485 (Lib) and https://github.com/FallenMoonNetwork/CanaryRecode/commit/10d57800b06b310a79dc4bbae6f251306f608d23 (Impl) address this
