### ISSUE TITLE
kit command is broke

### ISSUE THREAD

**Issue by darkdiplomat** [FallenMoonNetwork/CanaryLib#127]
Didn't add a group? well you get:
Caused by: java.lang.NullPointerException
at java.util.Arrays$ArrayList. (Arrays.java:2842)
at java.util.Arrays.asList(Arrays.java:2828)
at net.canarymod.backbone.BackboneKits.addKit(BackboneKits.java:53)
at net.canarymod.kit.KitProvider.addKit(KitProvider.java:28)
at net.canarymod.commandsys.commands.KitCommand.player(KitCommand.java:113)
at net.canarymod.commandsys.commands.KitCommand.execute(KitCommand.java:23)
at net.canarymod.commandsys.CommandList.kitCommand(CommandList.java:491)

Added a group? Well here's another error:
Caused by: java.lang.NullPointerException
at net.canarymod.Canary.serialize(Canary.java:278)
at net.canarymod.kit.Kit.getItemsAsStringList(Kit.java:146)
at net.canarymod.backbone.BackboneKits.addKit(BackboneKits.java:54)
at net.canarymod.kit.KitProvider.addKit(KitProvider.java:28)
at net.canarymod.commandsys.commands.KitCommand.player(KitCommand.java:138)
at net.canarymod.commandsys.commands.KitCommand.execute(KitCommand.java:23)
at net.canarymod.commandsys.CommandList.kitCommand(CommandList.java:491)

**Comment by darkdiplomat** [comment]
Actually now just kit give is broken
