### ISSUE TITLE
Deleting inherited groups error

### ISSUE THREAD

**Issue by BluXDragon** [FallenMoonNetwork/CanaryLib#155]
Deleting a group that is currently inherited throws an error (which makes sense);
`2013-12-12 17:15:02 [WARNING] [CanaryMod] Could not execute command...
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
        at java.util.ArrayList$Itr.next(Unknown Source)
        at net.canarymod.user.UserAndGroupsProvider.removeGroup(UserAndGroupsProvider.java:94)
        at net.canarymod.commandsys.commands.group.GroupRemove.execute(GroupRemove.java:39)
        at net.canarymod.commandsys.CommandList.groupRemove(CommandList.java:343)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.canarymod.commandsys.CommandManager$1.execute(CommandManager.java:299)
        at net.canarymod.commandsys.CanaryCommand.parseCommand(CanaryCommand.java:71)
        at net.canarymod.commandsys.CommandManager.parseCommand(CommandManager.java:178)
        at net.canarymod.api.CanaryServer.consoleCommand(CanaryServer.java:137)
        at net.minecraft.server.DedicatedServer.as(DedicatedServer.java:235)
        at net.minecraft.server.DedicatedServer.t(DedicatedServer.java:205)
        at net.minecraft.server.MinecraftServer.s(MinecraftServer.java:432)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:361)
        at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:13)`

Firstly, it should say something along the lines of "You cannot delete a group that is currently inherited by another!" or something of the sort, but this isn't the issue. The issue is that this error is still thrown even after deleting the inheriting group, until you issue the /reload command.

Here's a simple example. By default, the group "admins" inherits "mods". If I try to delete "mods", it throws the error above and nothing happens. 
I then delete "admins", which works just fine. Now that mods is the top group, you would expect to be able to delete it safely, however it still throws the same error and does nothing else.

A simple fix would be to reload the groups upon deleting one.

**Comment by BluXDragon** [comment]
Closed due to being in the wrong git.
