### ISSUE TITLE
Overriding commands causes an error (that breaks sethome, setwarp, warps, and create kit)

### ISSUE THREAD

**Issue by BluXDragon** [FallenMoonNetwork/CanaryLib#67]
```
Canary.commands().registerCommands(new PluginCommandListenerClass(), this, true);
```

The true on the end is meant to allow the force overriding of commands. While the new commands work (although the new commands work if set to false too), it throws this error;

```
Exception in thread "main" net.canarymod.commandsys.DuplicateCommandException: The command me msg tell  already exists!
        at net.canarymod.commandsys.CommandManager.registerCommands(CommandManager.java:337)
        at net.canarymod.commandsys.CommandManager.registerCommands(CommandManager.java:138)
        at net.canarymod.CanaryMod.initCommands(CanaryMod.java:77)
        at net.canarymod.Main.main(Main.java:48)
```

Which causes some default canary commands to cease functioning. In the above example I tried overwriting /me /msg and /tell

**Comment by ayyron-dev** [comment]
I closed the wrong one :3

**Comment by damagefilter** [comment]
Did that happen again in the last time or can we mark it as fixed?

**Comment by damagefilter** [comment]
A mark this as fixed. It's not reproducible anymore.
