### ISSUE TITLE
"Already Decorating!" semicrash error. Just posted chatlog inside <.<

### ISSUE THREAD

**Issue by BluXDragon** [FallenMoonNetwork/CanaryLib#73]
```
[01:50] <darkdiplomat> that is interesting
[01:50] <darkdiplomat> what were you trying to do?
[01:51] <BluXDragon> Well I wasn't doing anything in particular
[01:51] <BluXDragon> a player of mine was running around generating terrain, so it must have been related to that. I think there must have been a physics update on the very edge of the generated/loaded map.
[01:51] <BluXDragon> The plugin was, at the time, set to deny physics update in a 5m cube around sponge blocks
[01:51] <darkdiplomat> could have been
[01:52] <BluXDragon> Which means if there was a physics update at the edge of a new chunk, it would have tried to check a chunk that doesn't exist
[01:52] <BluXDragon> That's my best guess.

[02:59] <damagefilter> BluX_Srv: already decorating!!! comes from the chunk generator indeed and is thrown when a Decorator instance is told to do the terrain decoration while it already is doing that.
[03:01] <damagefilter> I suppose that'll be a thing with the hook in question not exiting properly or not continuing the code flow correctly. one of those things
[03:01] <damagefilter> did it crash?

[15:08] <BluX_Srv> damagefilter|away, yes the server crashed. Kind of. I was able to get back in but it crashed again. It was weird.

[16:14] <damagefilter> BluXDragon make an issue about that chunk thing please. I need to get some rest now. Will do that and sethome [player] tomorrow.
```

```
2013-05-10 01:38:46 [WARNING] [CanaryMod] Exception while executing Hook: BlockPhysicsHook in PluginListener: SuperSpongeListener (Plugin: SuperSponge)
net.canarymod.hook.HookExecutionException
        at net.canarymod.hook.HookExecutor$1.execute(HookExecutor.java:68)
        at net.canarymod.plugin.RegisteredPluginListener.execute(RegisteredPluginListener.java:55)
        at net.canarymod.hook.HookExecutor.callHook(HookExecutor.java:111)
        at net.minecraft.server.BlockSand.a(BlockSand.java:27)
        at net.minecraft.server.Chunk.a(Chunk.java:492)
        at net.minecraft.server.Chunk.a(Chunk.java:371)
        at net.minecraft.server.World.f(World.java:269)
        at net.minecraft.server.WorldGenSand.a(WorldGenSand.java:32)
        at net.minecraft.server.BiomeDecorator.a(BiomeDecorator.java:104)
        at net.minecraft.server.BiomeDecorator.a(BiomeDecorator.java:88)
        at net.minecraft.server.BiomeGenBase.a(BiomeGenBase.java:177)
        at net.minecraft.server.ChunkProviderGenerate.a(ChunkProviderGenerate.java:385)
        at net.minecraft.server.ChunkProviderServer.a(ChunkProviderServer.java:194)
        at net.minecraft.server.Chunk.a(Chunk.java:835)
        at net.minecraft.server.ChunkProviderServer.c(ChunkProviderServer.java:129)
        at net.minecraft.server.PlayerInstance.<init>(PlayerInstance.java:24)
        at net.minecraft.server.PlayerManager.a(PlayerManager.java:59)
        at net.minecraft.server.PlayerManager.d(PlayerManager.java:179)
        at net.minecraft.server.ServerConfigurationManager.d(ServerConfigurationManager.java:233)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:314)
        at net.minecraft.server.Packet10Flying.a(Packet10Flying.java:22)
        at net.minecraft.server.TcpConnection.b(TcpConnection.java:284)
        at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:72)
        at net.minecraft.server.NetworkListenThread.b(NetworkListenThread.java:32)
        at net.minecraft.server.DedicatedServerListenThread.b(DedicatedServerListenThread.java:24)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:477)
        at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:197)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:392)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:331)
        at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:13)
Caused by: net.minecraft.server.ReportedException: Exception getting block type in world
        at net.minecraft.server.World.a(World.java:179)
        at net.canarymod.api.world.CanaryWorld.getBlockAt(CanaryWorld.java:176)
        at com.bluxdragon.supersponge.SuperSpongeListener.isSpongeNear(SuperSpongeListener.java:128)
        at com.bluxdragon.supersponge.SuperSpongeListener.isSpongeNear(SuperSpongeListener.java:136)
        at com.bluxdragon.supersponge.SuperSpongeListener.onBlockPhysics(SuperSpongeListener.java:62)
        at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.canarymod.hook.HookExecutor$1.execute(HookExecutor.java:62)
        ... 29 more
Caused by: java.lang.RuntimeException: Already decorating!!
        at net.minecraft.server.BiomeDecorator.a(BiomeDecorator.java:82)
        at net.minecraft.server.BiomeGenBase.a(BiomeGenBase.java:177)
        at net.minecraft.server.ChunkProviderGenerate.a(ChunkProviderGenerate.java:385)
        at net.minecraft.server.ChunkProviderServer.a(ChunkProviderServer.java:194)
        at net.minecraft.server.Chunk.a(Chunk.java:835)
        at net.minecraft.server.ChunkProviderServer.c(ChunkProviderServer.java:129)
        at net.minecraft.server.ChunkProviderServer.d(ChunkProviderServer.java:138)
        at net.minecraft.server.World.e(World.java:241)
        at net.minecraft.server.World.a(World.java:171)
        ... 37 more
```

**Comment by damagefilter** [comment]
This'll be fun.

**Comment by damagefilter** [comment]
This may or may not be fixed ... Not sure. Reopen it if the error pops up again.
