### ISSUE TITLE
CompoundTag.values() issue

### ISSUE THREAD

**Issue by BluXDragon** [FallenMoonNetwork/CanaryLib#80]
The below code causes the below-below issue.

```
public static void checkNBT(MessageReceiver caller, CompoundTag nbt, boolean fromFile){
    for (BaseTag bt : nbt.values()){};
}
```

```
2013-05-16 02:09:27 [WARNING] [CanaryMod] Could not execute command: null
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.canarymod.commandsys.CommandManager$1.execute(CommandManager.java:254)
        at net.canarymod.commandsys.CanaryCommand.parseCommand(CanaryCommand.java:63)
        at net.canarymod.commandsys.CommandManager.parseCommand(CommandManager.java:134)
        at net.canarymod.api.entity.living.humanoid.CanaryPlayer.executeCommand(CanaryPlayer.java:297)
        at net.canarymod.api.entity.living.humanoid.CanaryPlayer.chat(CanaryPlayer.java:105)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:611)
        at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:40)
        at net.minecraft.server.TcpConnection.b(TcpConnection.java:284)
        at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:71)
        at net.minecraft.server.NetworkListenThread.b(NetworkListenThread.java:32)
        at net.minecraft.server.DedicatedServerListenThread.b(DedicatedServerListenThread.java:24)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:477)
        at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:199)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:392)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:331)
        at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:13)
Caused by: java.lang.ClassCastException: net.minecraft.server.NBTTagList cannot be cast to net.canarymod.api.nbt.BaseTag
        at com.bluxdragon.bxcommons.BxCommonsNBT.checkNBT(BxCommonsNBT.java:52)
        at com.bluxdragon.bxcommons.BxCommonsCommands.onBxCommandMetaEntity(BxCommonsCommands.java:123)
        ... 20 more
```

**Comment by darkdiplomat** [comment]
and fixed https://github.com/FallenMoonNetwork/CanaryRecode/commit/d3023aadd421f43cf93a9045bf0451ed9d426d0f
