### ISSUE TITLE
Error when doing a getServer().getPlayerNameList() while having a empty server.

### ISSUE THREAD

**Issue by greatman** [FallenMoonNetwork/CanaryLib#85]
Exception in thread "MCStats / Plugin Metrics" java.lang.NullPointerException
        at net.minecraft.server.MinecraftServer.getConfigurationManager(Minecraf
tServer.java:1064)
        at net.canarymod.api.CanaryServer.getPlayerList(CanaryServer.java:241)
        at net.canarymod.api.CanaryServer.getPlayerNameList(CanaryServer.java:10
0)
        at com.greatmancode.tools.caller.canary.CanaryCaller.getOnlinePlayers(Ca
naryCaller.java:189)
        at com.greatmancode.tools.utils.Metrics.getPlayersOnline(Metrics.java:19
4)
        at com.greatmancode.tools.utils.Metrics.postPlugin(Metrics.java:394)
        at com.greatmancode.tools.utils.Metrics.access$400(Metrics.java:83)
        at com.greatmancode.tools.utils.Metrics$1.run(Metrics.java:300)
        at java.lang.Thread.run(Unknown Source)

This is on build #440 of CanaryRecode.

**Comment by damagefilter** [comment]
Tested in enable() and during runtime.
Did not occur anymore.
