### ISSUE TITLE
Reloading Plugins causes CNFE

### ISSUE THREAD

**Issue by damagefilter** [FallenMoonNetwork/CanaryLib#93]
Example: Cuboids2.
After reloading, everythign and anything but the main-class will not load, instead error out with CNFE. It MIGHT has to do with Loader.findClass(...).
Here's a stacktrace:

```
2013-05-25 13:32:27 [WARNING] [CanaryMod] Exception while executing BlockUpdateHook in Cuboids2.BlockListener
net.canarymod.hook.HookExecutionException
    at net.canarymod.hook.HookExecutor$1.execute(HookExecutor.java:68)
    at net.canarymod.plugin.RegisteredPluginListener.execute(RegisteredPluginListener.java:55)
    at net.canarymod.hook.HookExecutor.callHook(HookExecutor.java:111)
    at net.minecraft.server.World.f(World.java:266)
    at net.minecraft.server.EntityAIEatGrass.e(EntityAIEatGrass.java:57)
    at net.minecraft.server.EntityAITasks.a(EntityAITasks.java:98)
    at net.minecraft.server.EntityLiving.bo(EntityLiving.java:1467)
    at net.minecraft.server.EntitySheep.bo(EntitySheep.java:42)
    at net.minecraft.server.EntityLiving.c(EntityLiving.java:1260)
    at net.minecraft.server.EntityAgeable.c(EntityAgeable.java:69)
    at net.minecraft.server.EntityAnimal.c(EntityAnimal.java:23)
    at net.minecraft.server.EntitySheep.c(EntitySheep.java:50)
    at net.minecraft.server.EntityLiving.l_(EntityLiving.java:529)
    at net.minecraft.server.World.a(World.java:1287)
    at net.minecraft.server.WorldServer.a(WorldServer.java:509)
    at net.minecraft.server.World.g(World.java:1268)
    at net.minecraft.server.World.h(World.java:1169)
    at net.minecraft.server.WorldServer.h(WorldServer.java:380)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:464)
    at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:207)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:396)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:335)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:13)
Caused by: java.lang.NoClassDefFoundError: net/playblack/cuboids/blocks/ChestBlock
    at net.playblack.cuboids.impl.canarymod.BlockListener.onBlockUpdate(BlockListener.java:255)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at net.canarymod.hook.HookExecutor$1.execute(HookExecutor.java:62)
    ... 22 more
```

**Comment by darkdiplomat** [comment]
Fixed with https://github.com/FallenMoonNetwork/CanaryLib/commit/28031f40d3784d8d1581011c7eca83cfc5e94071
